version: "3.8"
services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always
    networks:
      backend:
        aliases:
          - pihole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file: .env
    environment:
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - 'PIHOLE_DNS_=127.0.0.1#5053;127.0.0.1#5053'
      - DNS_FQDN_REQUIRED=true
      - DNS_BOGUS_PRIV=true
      - DNSSEC=true
      - REV_SERVER=true
      - REV_SERVER_CIDR=192.168.0.0/24
      - REV_SERVER_TARGET=192.168.0.1
      - REV_SERVER_DOMAIN=local
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: always
    network_mode: "service:unbound"
    cap_add:
      - CAP_NET_BIND_SERVICE
    depends_on:
      - unbound
  noip:
    container_name: noip
    image: mqll/noip:2.1.9-arm64
    volumes:
      - ./noip:/usr/local/etc
    restart: always
    networks:
      - backend
    depends_on:
      - pihole
  jellyfin:
    image: "hotio/jellyfin:release"
    container_name: jellyfin
    volumes:
        - ./jellyfin/config:/config
        - /media/DATA/media:/data
    env_file: .env
    ports:
      - "8096:8096"
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video10:/dev/video11"
      - "/dev/video10:/dev/video20"
      - "/dev/video10:/dev/video21"
      - "/dev/video10:/dev/video22"
      - "/dev/video10:/dev/video23"
      - "/dev/video10:/dev/video30"
      - "/dev/video10:/dev/video31"
    networks:
      - backend
    depends_on:
      - pihole
    restart: always
  mariadb:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
        - ./mariadb:/var/lib/mysql
    env_file: .env
    environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - backend
    depends_on:
      - pihole
  mync:
#    image: "nextcloud"
    build: nextcloud_dockerfile
    container_name: mync
    env_file: .env
    environment:
        - APACHE_DISABLE_REWRITE_IP=1
        - OVERWRITEWEBROOT=/nextcloud
        - TRUSTED_PROXIES=bunkerized-nginx
#        - NEXTCLOUD_TRUSTED_DOMAINS=${MY_DDNS_DOMAIN}
        - NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.127
        - NEXTCLOUD_DATA_DIR=/var/www/html/data
        - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
        - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
        - MYSQL_HOST=mariadb
    volumes:
        - ./nextcloud/html:/var/www/html
        - ./nextcloud/config:/var/www/html/config
        - /media/DATA:/data
    restart: always
    depends_on:
      - pihole
      - mariadb
    networks:
      - backend
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file: .env
    volumes:
      - ./wireguard/config:/config
      - /usr/src:/usr/src
    ports:
      - "51820:51820/udp"   #wireguard
      - "57967:57967"       #qbittorrent incoming port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    depends_on:
      - pihole
    networks:
      backend:
        aliases:
          - jackett
          - qbittorrent
          - flaresolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file: .env
    restart: always
    network_mode: "service:wireguard"
    depends_on:
      - pihole
      - wireguard
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    env_file: .env
    environment:
      - PUID=33
      - PGID=33
      - UMASK_SET=002
    volumes:
      - ./qbitorrent/config:/config
      - /media/DATA:/data
    network_mode: "service:wireguard"
    depends_on:
      - pihole
      - wireguard 
    restart: always
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    env_file: .env
    volumes:
      - ./jackett/config:/config
      - ./jackett/blackhole:/downloads
    restart: always
    network_mode: "service:wireguard"
    depends_on:
      - pihole
      - flaresolverr
      - wireguard
  sonarr:
    image: "hotio/sonarr:nightly"
    container_name: sonarr
    volumes:
        - ./sonarr/config:/config
        - /media/DATA:/data
    env_file: .env
    environment:
      - PUID=1001
      - PGID=33
    expose:
      - "8989"
    networks:
      - backend
    restart: always
    depends_on:
      - pihole
      - jackett
      - qbittorrent
  radarr:
    image: "hotio/radarr:nightly"
    container_name: radarr
    volumes:
        - ./radarr/config:/config
        - /media/DATA:/data
    env_file: .env
    environment:
      - PUID=1002
      - PGID=33
    expose:
      - "7878"
    networks:
      - backend
    restart: always
    depends_on:
      - pihole
      - jackett
      - qbittorrent
  lidarr:
    image: "hotio/lidarr:nightly"
    container_name: lidarr
    volumes:
        - ./lidarr/config:/config
        - /media/DATA:/data
    env_file: .env
    environment:
      - PUID=1003
      - PGID=33
    expose:
      - "8686"
    networks:
      - backend
    restart: always
    depends_on:
      - pihole
      - jackett
      - qbittorrent
  readarr:
    image: "hotio/readarr:nightly"
    container_name: readarr
    volumes:
        - ./readarr/config:/config
        - /media/DATA:/data
    env_file: .env
    environment:
      - PUID=1004
      - PGID=33
    expose:
      - "8787"
    networks:
      - backend
    restart: always
    depends_on:
      - pihole
      - jackett
      - qbittorrent
  bunkerized-nginx:
    image: "bunkerity/bunkerized-nginx"
    container_name: bunkerized-nginx
    volumes:
        - ./nginx/certificates:/etc/letsencrypt
        - ./server-confs:/server-confs:ro         
        - ./modsec-crs-confs:/modsec-crs-confs:ro 
        - ./modsec-confs:/modsec-confs:ro         
    env_file: .env
    environment:
#        - SERVER_NAME=${MY_DDNS_DOMAIN}
#        - AUTO_LETS_ENCRYPT=yes
#        - REDIRECT_HTTP_TO_HTTPS=yes
        - MAX_CLIENT_SIZE=0
        - USE_REVERSE_PROXY=yes
        - SERVE_FILES=no
        - REVERSE_PROXY_URL_1=/jackett/
        - REVERSE_PROXY_HOST_1=http://jackett:9117/
        - REVERSE_PROXY_URL_2=/sonarr
        - REVERSE_PROXY_HOST_2=http://sonarr:8989
        - REVERSE_PROXY_URL_3=/radarr
        - REVERSE_PROXY_HOST_3=http://radarr:7878
        - REVERSE_PROXY_URL_4=/lidarr
        - REVERSE_PROXY_HOST_4=http://lidarr:8686
        - REVERSE_PROXY_URL_5=/readarr
        - REVERSE_PROXY_HOST_5=http://readarr:8787
        - REVERSE_PROXY_URL_6=/jellyfin/
        - REVERSE_PROXY_HOST_6=http://jellyfin:8096/
        - REVERSE_PROXY_URL_7=/pihole/
        - REVERSE_PROXY_HOST_7=http://pihole/
        - REVERSE_PROXY_URL_8=/nextcloud/
        - REVERSE_PROXY_HOST_8=http://mync/
        - REVERSE_PROXY_URL_9=/qbittorrent/
        - REVERSE_PROXY_HOST_9=http://qbittorrent:8080/
        - ALLOWED_METHODS=GET|POST|HEAD|PROPFIND|DELETE|PUT|MKCOL|MOVE|COPY|PROPPATCH|REPORT
        - USE_BROTLI=yes
        - USE_GZIP=yes
        - X_FRAME_OPTIONS=SAMEORIGIN
        - REFERRER_POLICY=same-origin
        - PROXY_REAL_IP=yes
        - FAIL2BAN_STATUS_CODE=400|401|403|405|444
    ports:
        - "80:8080"
        - "443:8443"
    networks:
        - frontend
        - backend      
    restart: always
    depends_on:
      - mync
      - jackett
      - sonarr
      - radarr
      - lidarr
      - readarr
      - jellyfin
      - qbittorrent
      - pihole
      - wireguard

networks:
    frontend:
    backend:
      external: false
